# Site settings
title: "rachel"
bye_message: 'theme=gildasio/clyell; generator=jekyll; host=github'
baseurl: "https://rchan.dev/"
url: "/"

# Header settings
nick: "rachel"
mail:
    domain: "cs.toronto"
    ext: "edu"
source_code:
    server: "github.com"
    nick: "rcwchan"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-sitemap
