# Site settings
title: "rachel"
bye_message: 'theme="gildasio/clyell"'
baseurl: "https://rcwchan.github.io"
url: "https://rcwchan.github.io"

# Header settings
nick: "rachel"
mail:
    domain: "cs.toronto"
    ext: "edu"
source_code:
    server: "github.com"
    nick: "rcwchan"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
