# Site settings
title: "rachel"
bye_message: 'theme="gildasio/clyell"'
baseurl: "/"
url: "https://rcwchan.github.io"

# Header settings
nick: "rachel"
mail:
    domain: "cs.toronto"
    ext: "edu"
source_code:
    server: "github.com"
    nick: "rcwchan"
    #fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
